steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "training.dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/forecasting-training",
        "--network",
        "cloudbuild",
        ".",
      ]
    id: "build container image"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/forecasting-training"]
    id: "push container image to container registry"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "gcr.io/$PROJECT_ID/forecasting-training",
        "-e",
        "GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/key.json",
        "-v",
        "$GOOGLE_APPLICATION_CREDENTIALS:/tmp/keys/key.json:ro",
      ]
    id: "run container"
substitutions:
  _HOME: $HOME
timeout: 3600s
images:
  - gcr.io/$PROJECT_ID/forecasting-training
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
