name: Load final features
inputs:
- {name: data_bucket_name, type: String}
outputs:
- {name: Output, type: String}
implementation:
  container:
    image: python:3.10-slim
    command:
    - sh
    - -c
    - |2

      if ! [ -x "$(command -v pip)" ]; then
          python3 -m ensurepip || python3 -m ensurepip --user || apt-get install python3-pip
      fi

      PIP_DISABLE_PIP_VERSION_CHECK=1 python3 -m pip install --quiet     --no-warn-script-location 'kfp==1.8.13' && "$0" "$@"
    - sh
    - -ec
    - |
      program_path=$(mktemp -d)
      printf "%s" "$0" > "$program_path/ephemeral_component.py"
      python3 -m kfp.v2.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"
    - |2+

      import kfp
      from kfp.v2 import dsl
      from kfp.v2.dsl import *
      from typing import *

      def load_final_features(data_bucket_name: str) -> str:
          import os
          import json
          with open(os.path.join('gcs', data_bucket_name, 'final_features.json'),
                    'r') as final_features_file:
              final_features = json.loads(final_features_file.read())
          return json.dumps(final_features)

    args:
    - --executor_input
    - {executorInput: null}
    - --function_to_execute
    - load_final_features
